/**
 * Optimizely CMS SDK initialization
 *
 * This module initializes all Optimizely registries. Import this file
 * in your root layout or instrumentation file to ensure registries
 * are set up before any CMS content is rendered.
 */

import { initialize as initContentRegistries } from '@/content-types/registry';
import { initForms, initReactComponentRegistry } from '@optimizely/cms-sdk/react/server';
import * as components from '@/components';
import FormContainer from '@/components/forms/FormContainer';
import FormInput from '@/components/forms/FormInput';
import FormTextarea from '@/components/forms/FormTextarea';
import FormButton from '@/components/forms/FormButton';
import FormChoice from '@/components/forms/FormChoice';
import FormSelection from '@/components/forms/FormSelection';
import FormRange from '@/components/forms/FormRange';

// Registers every content type + display template pulled from the CMS.
// src/content-types/registry.ts is regenerated by `npm run cms:pull` and
// patched by `npm run sync` to fold in BlankExperienceContentType (an
// SDK-builtin, not sourced from the CMS) — don't hand-edit it.
initContentRegistries();

// Initialize React component registry for server-side rendering
initReactComponentRegistry({
  resolver: {
    ArticlePage: components.ArticlePage,
    CardBlock: components.CardBlock,
    HeroBlock: components.HeroBlock,
    RichTextElement: components.RichTextElement,
    TextElement: components.TextElement,
    ImageElement: components.ImageElement,
    BlankExperience: components.BlankExperience,
    BlankSection: components.BlankSection,
    StandardExperience: components.StandardExperience,
    SideNavBlock: components.SideNavBlock,
    ImageMedia: components.ImageMedia,
  },
});

// Optimizely Forms: registers the SDK's built-in form content types and the
// components that render them. Independent of the registries above — forms
// aren't pulled from the CMS via `config pull`, so this isn't touched by
// `npm run sync`. See node_modules/@optimizely/cms-sdk/docs/15-forms.md.
initForms({
  container: FormContainer,
  textbox: FormInput,
  number: FormInput,
  url: FormInput,
  textarea: FormTextarea,
  choice: FormChoice,
  selection: FormSelection,
  range: FormRange,
  submit: FormButton,
  reset: FormButton,
});