/**
 * Optimizely CMS SDK initialization
 *
 * This module initializes all Optimizely registries. Import this file
 * in your root layout or instrumentation file to ensure registries
 * are set up before any CMS content is rendered.
 */

import { initialize as initContentRegistries } from '@/content-types/registry';
import { initReactComponentRegistry } from '@optimizely/cms-sdk/react/server';
import * as components from '@/components';

// Registers every content type + display template pulled from the CMS.
// src/content-types/registry.ts is regenerated by `npm run cms:pull` and
// patched by `npm run sync` to fold in BlankExperienceContentType (an
// SDK-builtin, not sourced from the CMS) — don't hand-edit it.
initContentRegistries();

// Initialize React component registry for server-side rendering
initReactComponentRegistry({
  resolver: {
    ArticlePage: components.ArticlePage,
    CardBlock: components.CardBlock,
    HeroBlock: components.HeroBlock,
    RichTextElement: components.RichTextElement,
    TextElement: components.TextElement,
    ImageElement: components.ImageElement,
    BlankExperience: components.BlankExperience,
    BlankSection: components.BlankSection,
    StandardExperience: components.StandardExperience,
    SideNavBlock: components.SideNavBlock,
    ImageMedia: components.ImageMedia,
  },
});